auth_app/urls.py
from django.urls import path
from .views import Registration, Login, Logout, Verification
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("register/", Registration.as_view(), name="register"),
    path("login/", Login.as_view(), name="login"),
    path("activate-account/<uidb64>/<token>", Verification.as_view(), name="activate"),
    path("logout", Logout.as_view(), name="logout"),
    path(
        "reset-password/",
        auth_views.PasswordResetView.as_view(
            template_name="auth_app/reset_password.html"
        ),
        name="password_reset",
    ),
    path(
        "reset-password_sent/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="auth_app/reset_password_sent.html"
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="auth_app/set_new_password.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset-password-complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="auth_app/reset_password_done.html"
        ),
        name="password_reset_complete",
    ),
]

expense_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.conf import settings
from . import views

urlpatterns = [
    path("", TemplateView.as_view(template_name="index.html"), name="index"),
    path(
        "download-data/",
        TemplateView.as_view(template_name="download_data.html"),
        name="download_data",
    ),
    path(
        "download-data/complete-spreadsheet/excel",
        views.complete_spreadsheet_excel,
        name="complete_spreadsheet_excel",
    ),
    path(
        "download-data/complete-spreadsheet/csv",
        views.complete_spreadsheet_csv,
        name="complete_spreadsheet_csv",
    ),
    path(
        "download-data/complete-spreadsheet/pdf",
        views.complete_spreadsheet_pdf,
        name="complete_spreadsheet_pdf",
    ),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("auth/", include("auth_app.urls")),
    path("expense/", include("expense_app.urls")),
    path("income/", include("income_app.urls")),
    path("invest/", include("invest_app.urls")),
    path("user/", include("user_profile.urls")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "Expense Income Tracker Admin"
admin.site.index_title = "Expense-Income-Tracker"

invest_app/urls.py
from invest_app.views import (
    DeleteStock,
    EditStock,
    SectorView,
    StockD,
    StockView,
    SectorD,
    EditSector,
    DeleteSector,
    stock_page,
    StockPortfolioView,
    add_stock_page,
)
from .routers import DefaultRouter
from django.urls import path, include

router = DefaultRouter(trailing_slash=False)

router.register(r"sector", SectorView, basename="sector")
router.register(r"stock", StockView, basename="stock")
router.register(r"stock-portfolio", StockPortfolioView, basename="stock_portfolio")
#

urlpatterns = [
    path("", include(router.urls)),
    # Templating purpose
    path("add-sector/", SectorD, name="add_sector"),
    path("edit-sector/<int:pk>/", EditSector, name="edit_sector"),
    path("delete-sector/<int:pk>/", DeleteSector, name="delete_sector"),
    path("add-stock/", StockD, name="add_stock"),
    path("edit-stock/<int:pk>/", EditStock, name="edit_stock"),
    path("delete-stock/<int:pk>/", DeleteStock, name="delete_stock"),
    path("stocks/", stock_page, name="stocks"),
    path("add-stocks/", add_stock_page, name="add_stocks_details"),
]

invest_app/models.py
from django.db import models
from django.db.models import Sum
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User
from django.utils.timezone import localtime

# Create your models here.


class Sector(models.Model):
    sector_name = models.CharField(max_length=150)
    created_at = models.DateTimeField(default=localtime)

    def __str__(self):
        return self.sector_name

    class Meta:
        verbose_name_plural = "Sectors"


class Stock(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    sector = models.ForeignKey(Sector, on_delete=models.CASCADE)
    stock_name = models.CharField(max_length=150)
    stock_symbol = models.CharField(max_length=100)
    isin = models.CharField(
        max_length=15,
        help_text=" International Securities Identification Number",
        blank=True,
    )
    created_at = models.DateTimeField(default=localtime)

    def __str__(self):
        return self.stock_name

    class Meta:
        verbose_name_plural = "Stocks"


class Transaction(models.Model):
    """
    Model of Stock plan and amount
    """

    market = ((0, "Sell"), (1, "Buy"))
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    stock = models.ForeignKey(Stock, on_delete=models.CASCADE)
    market_choice = models.IntegerField(choices=market, default=1)
    qauntity = models.IntegerField()
    invested_amount = models.FloatField()
    last_profit = models.FloatField()
    last_closed = models.FloatField()
    interest_rate = models.FloatField()
    invested_date = models.DateTimeField(default=localtime)
    plan_of_investment_date = models.DateField(default=localtime)

    def __str__(self):
        return f"{self.stock_name} invested money : {self.invested_amount} and current amount: {self.actual_amount}"

    @property
    def monthly_interest(self):
        if not self.expected_amount:
            return self.expected_amount * self.interest_rate
        return self.invested_amount * self.interest_rate


class Goal(models.Model):
    duration = ((1, "Long Term"), (2, "Short Term"), (3, "Mid Term"))
    title = models.CharField(max_length=150, help_text="Goal Name", null=False)
    target_amount = models.FloatField(blank=True)
    term = models.IntegerField(choices=duration, default=1)
    create = models.DateTimeField(_("Date"), auto_now=True)
    last_update = models.DateTimeField(
        _("Till Date"), auto_now=False, auto_now_add=False
    )

    def __str__(self) -> str:
        return self.title

invest_app/views.py
from datetime import datetime
from django.contrib import messages
from django.shortcuts import redirect, render
from rest_framework.views import APIView
from invest_app.models import Stock, Transaction, Sector
from rest_framework import mixins
from rest_framework import generics
from invest_app.serializers import (
    SectorSerializer,
    StockInvestmentSerializer,
    StockSerializer,
)
from rest_framework import (
    filters,
    mixins,
    permissions,
    response,
    serializers,
    status,
    viewsets,
)
from django.db.models import Q
from django.core.paginator import Paginator
from user_profile.models import UserProfile


def SectorD(request):
    """
    List all Sectors, or create a new sector
    """
    context = {"sources": Sector.objects.all()}
    if request.method == "POST":
        sector = request.POST.get("sector_name")
        sources = Sector()
        sources.sector_name = sector
        sources.created_at = datetime.now()
        sources.save()
        messages.info(request, f"Sector is Added {sources}")
        return redirect("add_sector")

    return render(request, "invest_app/add_sector.html", context)


def EditSector(request, pk):
    """
    List all Sectors, or create a new sector
    """
    if request.method == "POST":
        sector = request.POST.get("sector_name")
        sources = Sector.objects.get(id=pk)
        sources.sector_name = sector
        sources.created_at = datetime.now()
        sources.save()
        messages.info(request, "Sector updated")
        return redirect("add_sector")
    context = {"sources": Sector.objects.all(), "values": Sector.objects.get(id=pk)}
    return render(request, "invest_app/edit_sector.html", context)


def DeleteSector(request, pk):
    """
    List all Sectors, or create a new sector
    """
    if request.method == "GET":
        sources = Sector.objects.get(id=pk)
        sources.delete()
        messages.info(request, "Sector deleted")
        return redirect("add_sector")


def StockD(request):
    """
    List all Sectors, or create a new sector
    """
    context = {"sources": Stock.objects.all(), "sectors": Sector.objects.all()}

    if request.method == "POST":
        stock = request.POST.get("stock_name")
        sector_value = request.POST.get("sector")
        stock_symbol = request.POST.get("stock_symbol")
        isin = request.POST.get("isin")
        created_at = request.POST.get("created_at")
        sources = Stock()
        sources.user = request.user
        sources.sector = Sector.objects.get(id=sector_value)
        sources.stock_name = stock
        sources.stock_symbol = stock_symbol
        sources.isin = isin
        sources.created_at = created_at if created_at else datetime.now()
        sources.save()
        messages.info(request, f"Sector is Added {sources}")
        return redirect("add_stock")

    return render(request, "invest_app/add_stock.html", context)


def EditStock(request, pk):
    """
    List all Sectors, or create a new sector
    """
    if request.method == "POST":
        stock = request.POST.get("stock_name")
        sector_value = request.POST.get("sector")
        stock_symbol = request.POST.get("stock_symbol")
        isin = request.POST.get("isin")
        created_at = request.POST.get("created_at")
        sources = Stock.objects.get(pk=pk)
        sources.user = request.user
        sources.sector = Sector.objects.get(id=sector_value)
        sources.stock_name = stock
        sources.stock_symbol = stock_symbol
        sources.isin = isin
        sources.created_at = created_at if created_at else datetime.now()
        sources.save()
        messages.info(request, "Stock updated")
        return redirect("add_stock")
    context = {
        "sources": Stock.objects.all(),
        "values": Stock.objects.get(id=pk),
        "sectors": Sector.objects.all(),
    }
    return render(request, "invest_app/edit_stock.html", context)


def DeleteStock(request, pk):
    """
    List all Sectors, or create a new sector
    """
    if request.method == "GET":
        sources = Stock.objects.get(id=pk)
        sources.delete()
        messages.info(request, "Stock deleted")
        return redirect("add_stock")


def stock_page(request):

    filter_context = {}
    base_url = f""
    date_from_html = ""
    date_to_html = ""

    incomes = Transaction.objects.filter(user=request.user).order_by("-invested_date")

    try:

        if "date_from" in request.GET and request.GET["date_from"] != "":
            date_from = datetime.strptime(request.GET["date_from"], "%Y-%m-%d")
            filter_context["date_from"] = request.GET["date_from"]
            date_from_html = request.GET["date_from"]

            if "date_to" in request.GET and request.GET["created_at"] != "":

                date_to = datetime.strptime(request.GET["date_to"], "%Y-%m-%d")
                filter_context["date_to"] = request.GET["date_to"]
                date_to_html = request.GET["date_to"]
                incomes = incomes.filter(
                    Q(date__gte=date_from) & Q(date__lte=date_to)
                ).order_by("-date")

            else:
                incomes = Transaction.filter(date__gte=date_from).order_by(
                    "-invested_date"
                )

        elif "date_to" in request.GET and request.GET["created_at"] != "":

            date_to_html = request.GET["created_at"]
            date_to = datetime.strptime(request.GET["date_to"], "%Y-%m-%d")
            filter_context["date_from"] = request.GET["date_to"]
            incomes = incomes.filter(date__lte=date_to).order_by("-invested_date")

    except:
        messages.error(request, "Something went wrong")
        return redirect("stocks")

    base_url = f"?date_from={date_from_html}&date_to={date_to_html}&"
    paginator = Paginator(incomes, 5)
    page_number = request.GET.get("page")
    page_incomes = Paginator.get_page(paginator, page_number)

    if UserProfile.objects.filter(user=request.user).exists():
        currency = UserProfile.objects.get(user=request.user).currency
    else:
        currency = "INR - Indian Rupee"

    return render(
        request,
        "invest_app/stocks.html",
        {
            "currency": currency,
            "page_incomes": page_incomes,
            "incomes": incomes,
            "filter_context": filter_context,
            "base_url": base_url,
        },
    )


def add_stock_page(request):
    context = {"sources": Stock.objects.all()}
    if request.method == "POST":
        stock = request.POST.get("stock")
        market_choice = request.POST.get("market_choice")
        qauntity = request.POST.get("qauntity")
        invested_amount = request.POST.get("invested_amount")
        last_profit = request.POST.get("last_profit")
        last_closed = request.POST.get("last_closed")
        interest_rate = request.POST.get("interest_rate")
        plan_of_investment_date = request.POST.get("plan_of_investment_date")
        stock_details = Transaction()
        stock_details.stock = Stock.objects.get(stock_name=stock)
        stock_details.user = request.user
        stock_details.market_choice = market_choice
        stock_details.qauntity = qauntity
        stock_details.interest_rate = interest_rate
        stock_details.last_closed = last_closed
        stock_details.last_profit = last_profit
        stock_details.invested_amount = invested_amount
        stock_details.invested_date = datetime.now()
        stock_details.plan_of_investment_date = plan_of_investment_date

        stock_details.save()

    return render(request, "invest_app/stocktranscation.html", context)


"""'

API for REST Framework

"""


class SectorView(
    mixins.ListModelMixin,
    viewsets.GenericViewSet,
    mixins.RetrieveModelMixin,
    mixins.CreateModelMixin,
    mixins.UpdateModelMixin,
):
    queryset = Sector.objects.all()
    serializer_class = SectorSerializer
    permission_classes = (permissions.IsAuthenticated,)

    def create(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        self.perform_create(serializer)
        return response.Response(serializer.data, status=status.HTTP_201_CREATED)

    def update(self, request, *args, **kwargs):
        permit = self.get_object()
        serializer = self.get_serializer(data=request.data, instance=permit)
        serializer.is_valid(raise_exception=True)
        self.perform_create(serializer)

        return response.Response(serializer.data)


class StockView(
    mixins.ListModelMixin,
    viewsets.GenericViewSet,
    mixins.RetrieveModelMixin,
    mixins.CreateModelMixin,
    mixins.UpdateModelMixin,
):
    queryset = Stock.objects.all()
    serializer_class = StockSerializer
    permission_classes = (permissions.IsAuthenticated,)

    def create(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        self.perform_create(serializer)
        return response.Response(serializer.data, status=status.HTTP_201_CREATED)

    def update(self, request, *args, **kwargs):
        permit = self.get_object()
        serializer = self.get_serializer(data=request.data, instance=permit)
        serializer.is_valid(raise_exception=True)
        self.perform_create(serializer)

        return response.Response(serializer.data)


class StockPortfolioView(
    mixins.ListModelMixin,
    viewsets.GenericViewSet,
    mixins.RetrieveModelMixin,
    mixins.CreateModelMixin,
    mixins.UpdateModelMixin,
):
    queryset = Transaction.objects.all()
    serializer_class = StockInvestmentSerializer
    permission_classes = (permissions.IsAuthenticated,)

    def create(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        self.perform_create(serializer)

templates/invest_app/add_sector.html
{% extends "base.html" %}
{% block title_main %}Add Sector{% endblock %}


{% block body_main %}
    {% include "partials/_sidebar_main.html" %}
  <div class="main-content bg-primary" id="panel">
    {% include "partials/_navbar_main.html" %}
    <div class="header bg-primary pb-6">
      <div class="mr-5 ml-5"><div class="mr-5 ml-5">{% include "partials/_messages.html" %}</div></div>
      <div class="container-fluid"><div class="header-body"><div class="row align-items-center py-4"><div class="col-lg-6 col-7"><nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4"><ol class="breadcrumb breadcrumb-links breadcrumb-dark"><li class="breadcrumb-item"><a href="{% url 'dashboard' %}"><i class="fas fa-home"></i></a></li><li class="breadcrumb-item"><a href="{% url 'income' %}">Sector</a></li><li class="breadcrumb-item active" aria-current="page">Add Sector</li></ol></nav></div></div></div></div>
    </div>
    <div class="container-fluid mt--6">
      <div class="row">
        <div class="col mr-5 ml-5">
          <div class="card">
            <div class="card-header bg-transparent">
              <div class="row align-items-center">  
                <div class="col">
                  <h5 class="h3 mb-0 text-center">Add Sector</h5>
                  <form action="{% url 'add_sector' %}" method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="">Sector Name</label>
                        <input class="form-control form-control-sm" type = "text" name="sector_name" value = "{{ values }}" >
                    </div>
                    <div class="text-center">
                        <button type="submit" class="btn btn-primary">Save Sector</button>
                    </div>
                </form>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="container-fluid mt-5">
          <div class="row">
            <div class="col mr-5 ml-5">
              <div class="card">
                <div class="card-header bg-transparent">
                  <div class="row align-items-center">  
                    <div class="col">
                      <h5 class="h3 mb-3 text-center">Sector List</h5>
                      <h6 class="h3 mb-3 text-center text-danger">Please Note: Deleting Source will also delete the sector which are linked with these stocks</h6>
                      {% if sources %}
                        <table class="table align-items-center table-flush">
                          <thead class="thead-light"><tr><th scope="col">Serial No.</th><th scope="col">Sector Name</th><th scope="col">Created At</th><th scope="col">Action</th></tr></thead>
                          <tbody>{% for source in sources %}<tr><td> {{forloop.counter}} </td><td> {{source.sector_name}} </td><td> {{source.created_at}} </td><td><a href="{% url 'edit_sector' source.id %}" class="btn btn-warning btn-sm">Edit</a><a href="{% url 'delete_sector' source.id %}" class="btn btn-danger btn-sm">Delete</a> </td></tr>{% endfor %}</tbody>
                        </table>
                      {% else %}
                        <div class="text-center text-danger mt-4">No Sector. Please Add Sectors</div>
                      {% endif %}
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/invest_app/investment_summary.html
{% extends "base.html" %}
{% load static %}
{% block title_main %}Income Summary{% endblock %}
{% block body_main %}
{% include "partials/_sidebar_main.html" %}
<div class="main-content" id="panel">
  {% include "partials/_navbar_main.html" %}
  <div class="header bg-primary pb-6">
    <div class="mr-5 ml-5">
      <div class="mr-5 ml-5">{% include "partials/_messages.html" %}</div>
    </div>
    <div class="container-fluid">
      <div class="header-body">
        <div class="row align-items-center py-4">
          <div class="col-lg-6 col-7">
            <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
              <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
                <li class="breadcrumb-item"><a href="{% url 'dashboard' %}"><i class="fas fa-home"></i></a></li>
                <li class="breadcrumb-item"><a href="{% url 'income' %}">Income</a></li>
                <li class="breadcrumb-item active" aria-current="page">Summary</li>
              </ol>
            </nav>
          </div>
          <div class="col-lg-6 col-5 text-right">
            <button id="today" class="btn btn btn-neutral">Today</button>
            <button id="week" class="btn btn btn-neutral">This Week</button>
            <button id="month" class="btn btn btn-neutral">This Month</button>
            <button id="six_month" class="btn btn btn-neutral">Last Six Month</button>
            <button id="year" class="btn btn btn-neutral">This Year</button></div>
        </div>
      </div>
    </div>
  </div>
  <div class="container-fluid mt--6">
    <div class="row">
      <div class="col">
        <div class="card bg-default">
          <div class="card-header bg-transparent">
            <div class="row align-items-center">
              <div class="col">
                <div class="chart-container" style="position: relative; height:500px; width: 1000px;">
                  <canvas id="myChart" class="chart-canvas chartjs-render-monitor" width="1000" height="500"></canvas>
                </div>
                <div class="text-center mt-5"><button id="dough" class="btn btn btn-neutral">Dough Nut</button><button
                    id="pie" class="btn btn btn-neutral">Pie</button><button id="bar"
                    class="btn btn btn-neutral">Bar</button><button id="polarArea" class="btn btn btn-neutral">Polar
                    Area</button></div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<script src="{% static 'js/income_summary.js' %}"></script>
{% endblock %}

templates/invest_app/stocks.html
{% extends "base.html" %}
{% load static %}
{% block title_main %}Stock Portfolio{% endblock %}
{% block body_main %}
{% load humanize %}
<link rel="stylesheet" href="{% static 'css/arrow.css' %}" type="text/css">
{% include "partials/_sidebar_main.html" %}
<div class="main-content" id="panel">
  {% include "partials/_navbar_main.html" %}
  <div class="header bg-primary pb-6">
    <div class="mr-5 ml-5">
      <div class="mr-5 ml-5">{% include "partials/_messages.html" %}</div>
    </div>
    <div class="container-fluid">
      <div class="header-body">
        <div class="row align-items-center py-4">
          <div class="col-lg-5 col-6">
            <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
              <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
                <li class="breadcrumb-item"><a href="{% url 'dashboard' %}"><i class="fas fa-home"></i></a></li>
                <li class="breadcrumb-item"><a href="{% url 'stocks' %}">Stock</a></li>
                <li class="breadcrumb-item active" aria-current="page">View</li>
              </ol>
            </nav>
          </div>
          <div class="col-md-3 text-right ml--5 mr-5">
            <div class="input-group input-group-alternative input-group-merge">
              <div class="input-group-prepend"><span
                  style="border-end-start-radius: 50%; border-start-start-radius: 50%;" class="input-group-text"><i
                    class="fas fa-search"></i></span></div><input class="form-control" id="searchField"
                placeholder="Search" type="text">
              <div class="input-group-append"><span style="border-end-end-radius: 50%; border-start-end-radius: 50%;"
                  class="input-group-text"></span></div>
            </div>
          </div>
          <div class="col-md-2 text-right ml-3 mr--3"><a href="{% url 'import_income' %}"
              class="btn btn btn-neutral">Import</a> </div>
          <div class="col-md-2 text-right ml--4"><a href="{% url 'add_stocks_details' %}" class="btn btn btn-neutral">Create
              New</a></div>
        </div>
        <hr class="mt--2" />
        <div class="row align-items-center py-4">
          <div class="col mt--5 ml-5">
            <form method="GET" class="form-inline ml-5" action="{% url 'income' %}">
              <div class="form-group"><span class="text-white ml-5">From: <input
                    class="ml-1 form-control form-control-sm col-md-8" id="date_from" name="date_from" type="date"
                    value="{{ filter_context.date_from }}" /></span></div>
              <div class="form-group"><span class="text-white ml-5">To: <input
                    class="ml-1 form-control form-control-sm col-md-9" id="date_to" name="date_to"
                    value="{{ filter_context.date_to }}" type="date" /></span></div>
              <div class="ml-5"><span class="ml-5"><button
                    class="ml-5 mr-3 btn btn-success btn-sm">Filter</button></span></div><button
                onclick="clearFilters()" class="mr-5 ml-2 btn btn-danger btn-sm">Clear</button>
            </form>
          </div>
        </div>
        <hr class="mt--2" />
      </div>
    </div>
  </div>
  <div class="container-fluid mt--6">
    <div class="row">
      <div class="col">
        <div class="card bg-default">
          <div class="card-header bg-transparent">
            <div class="row align-items-center">
              <div class="col">
                {% if incomes %}
                <h5 class="h3 text-white mb-0 text-center">My Stock Portfolio: <span id="income_count">{{ incomes.count }}</span>
                </h5>
                <div class="app-table mt-5">
                  <table id="table-complete" class="table text-white">
                    <thead>

                      <tr>
                        <th style="font-size: small;">Stock</th>
                        <th style="font-size: small;">Buy / Sell </th>

                        <th style="font-size: small;">
                          <span class="row">
                            Invested_amount ({{currency|truncatechars:3}})
                            <span class="col">
                              <div class="mb-1 arrow-up" id="amount_up"></div>
                              <div class="arrow-down" id="amount_down"></div>
                            </span>
                          </span>
                        </th>
                        <th style="font-size: small;">Plan Years</th>
                        <th style="font-size: small;">
                          <span class="row ml-1">
                            Invested date
                            <span class="col">
                              <div class="mb-1 arrow-up" id="date_up"></div>
                              <div class="arrow-down" id="date_down"></div>
                            </span>
                          </span>
                        </th>
                        <th style="font-size: small;">Action</th>
                      </tr>
                    </thead>
                    <tbody id="table-body-data">
                      {% for income in page_incomes %}
                      <tr>
                        <td>{{income.stock}}</td>
                        <td> {% if income.market_choice == 1 %}
                          <span style="color: #34e034;">{{income.get_market_choice_display }}</span>
                        {% else %}
                        <span style="color: #ee0000;">{{income.get_market_choice_display }}</span>
                        {% endif %}
                        </td>
                        <td>{{income.invested_amount|intcomma }}</td>
                        <td>{{income.plan_of_investment_date.year}}</td>
                        <td>{{income.invested_date}}</td>

                        <td><a href="{% url 'edit_income' income.id %}" class="btn btn-warning btn-sm">Edit</a></td>
                      </tr>
                      {% endfor %}
                    </tbody>
                  </table>
                </div>
                {% else %}
                <h5 class="h3 text-white mb-0 text-center">No incomes. Create <a href="{% url 'add_income' %}">one</a>
                </h5>
                {% endif %}
                <h5 style="display: none;" id="no-results" class="h3 text-danger mt-5 mb-0 text-center">No incomes found
                  for searched item.</h5>
              </div>
            </div>
          </div>
        </div>
        <div class="pagination-container">
          <div class="row">
            <div class="col-md-6">
              <p></p>
              <span class="text-white">Showing page {{page_incomes.number}} of {{ page_incomes.paginator.num_pages}}</span>
            </div>
            <div class="col-md-6">
              <ul class="pagination align-right float-right mr-auto">
                {% if page_incomes.has_previous %}
                <a class="btn btn-outline-default mb-4" href="{{base_url}}page=1">First</a>
                <a class="btn btn-outline-default mb-4"
                  href="{{base_url}}page={{ page_incomes.previous_page_number }}">Previous</a>
                {% endif %}
                {% for num in page_incomes.paginator.page_range %}
                {% if page_incomes.number == num %}
                <a class="btn btn-default mb-4" href="{{base_url}}page={{ num }}">{{ num }}</a>
                {% elif num > page_incomes.number|add:'-2' and num < page_incomes.number|add:'2' %} <a
                  class="btn btn-outline-default mb-4" href="{{base_url}}page={{ num }}">{{ num }}</a>
                  {% endif %}
                  {% endfor %}
                  {% if page_incomes.has_next %}
                  <a class="btn btn-outline-default mb-4"
                    href="{{base_url}}page={{ page_incomes.next_page_number }}">Next</a>
                  <a class="btn btn-outline-default mb-4"
                    href="{{base_url}}page={{ page_incomes.paginator.num_pages }}">Last</a>
                  {% endif %}
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<script src="{% static 'js/income_search.js' %}"></script>
<form method="GET" id="amount_up_form" action="{% url 'income_page_sort' %}">
  <input hidden name="amount_sort" value="2"></input>
</form>
<form method="GET" id="amount_down_form" action="{% url 'income_page_sort' %}">
  <input hidden name="amount_sort" value="1"></input>
</form>
<form method="GET" id="date_up_form" action="{% url 'income_page_sort' %}">
  <input hidden name="date_sort" value="2"></input>
</form>
<form method="GET" id="date_down_form" action="{% url 'income_page_sort' %}">
  <input hidden name="date_sort" value="1"></input>
</form>
<script src="{% static 'js/sorting.js' %}"></script>
{% endblock %}